<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKhtt2zj\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKhtt2zj/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKhtt2zj.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKhtt2zj\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKhtt2zj\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Khtt2zj',
    'container.build_id' => 'eb7b0085',
    'container.build_time' => 1654764643,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKhtt2zj');
