<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format'], ['variable', '/', '\\d+', 'code'], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token'], ['text', '/_profiler']], [], []],
    'admin_accueil' => [[], ['_controller' => 'App\\Controller\\AdminBundle\\AdminController::index'], [], [['text', '/admin/']], [], []],
    'app_admin_api_index' => [[], ['_controller' => 'App\\Controller\\AdminBundle\\ApiController::index'], [], [['text', '/api/users/lists']], [], []],
    'admin_charts' => [[], ['_controller' => 'App\\Controller\\AdminBundle\\ChartsController::index'], [], [['text', '/admin/charts']], [], []],
    'charts_pie' => [[], ['_controller' => 'App\\Controller\\AdminBundle\\ChartsController::pieChart'], [], [['text', '/admin/charts/pie']], [], []],
    'bar_charts' => [[], ['_controller' => 'App\\Controller\\AdminBundle\\ChartsController::barChart'], [], [['text', '/admin/charts/bar']], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeBundle\\HomeController::index'], [], [['text', '/']], [], []],
    'profile' => [[], ['_controller' => 'App\\Controller\\ProfileBundle\\ProfileController::index'], [], [['text', '/profile']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityBundle\\SecurityController::login'], [], [['text', '/login']], [], []],
    'user_registration' => [[], ['_controller' => 'App\\Controller\\SecurityBundle\\SecurityController::register'], [], [['text', '/register']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityBundle\\SecurityController::logout'], [], [['text', '/logout']], [], []],
];
